### PR TITLE
Add implicit transaction column to output 

### LINKED ISSUE #41: Add implicit transaction column to output
On servers using the JDBC driver and other smelly unfortunates, implicit transactions can be quite an annoying problem. I wrote code into sp_BlitzWho to identify them, and I'd love to get it in sp_WhoIsActive so I don't need to use another proc for it.

It looks something like this:

```
SELECT
    des.session_id,
    CASE 
        WHEN 
            EXISTS 
            (  
                SELECT 
                    1/0 
                FROM sys.dm_tran_active_transactions AS tat
                JOIN sys.dm_tran_session_transactions AS tst
                    ON tst.transaction_id = tat.transaction_id
                WHERE tat.name = 'implicit_transaction'
                AND des.session_id = tst.session_id 
            )  THEN 1 
        ELSE 0
    END
FROM sys.dm_exec_sessions AS des;
```

### PR DESCRIPTION
**Pull request by erikdarlingdata**
Closes #41

### CODE REVIEW

**Comment by amachanic** [comment]
This seems to not be complete, so I'm labeling it work in progress. Let me know if I've missed something.

**Comment by amachanic** [comment]
Did you consider making this part of `@get_transaction_info`?

**Comment by erikdarlingdata** [comment]
I did, but this seemed to be the path of least resistance for getting it in. If you’d rather it under that parameter, lemme know how you’d envision it being surfaced.

**Comment by amachanic** [comment]
@erikdarlingdata I tried to modify this and screwed something up. The diff now contains the entirety of the code. So I'm opening a new PR with my proposed implementation: https://github.com/amachanic/sp_whoisactive/pull/65

**Pull request closed without merging**
