### PR TITLE
Changed to trim extra latch info from waitresource

### LINKED ISSUE #56: An upcoming change in waitresource format will break sp_whoisactive
An upcoming change in Azure SQL and future versions of SQL Server will change the format of the waitresource column in sysprocesses and several DMVs to include additional latch diagnostics for all latch waits. For example, instead of `13:1:24323201` for a PAGEIOLATCH_EX wait, we will see `13:1:24323201 (LATCH 0x0000020114CC5FD8: CLASS: BUF_LATCH KP: 0 SH: 0 UP: 0 EX: 1 DT: 0 Sublatch: 0 HasWaiters: 1 Task: 0x000001FDF5F6FC28 AnyReleasor: 1)`.

On MSSQL builds with this change, sp_whoisactive v11.35 fails with `Msg 245, Level 16, State 1, Line 331
Conversion failed when converting the nvarchar value ' 1)' to data type int.`

A crude but straightforward fix for this would be to replace `RTRIM(sp2.waitresource)` on lines https://github.com/amachanic/sp_whoisactive/blob/459d2bcef5474baaf5a9e207ab60ee2f55ab48b2/who_is_active.sql#L1993 and https://github.com/amachanic/sp_whoisactive/blob/459d2bcef5474baaf5a9e207ab60ee2f55ab48b2/who_is_active.sql#L2074 with `CASE WHEN CHARINDEX('' (LATCH '', sp2.waitresource) > 0 THEN LEFT(sp2.waitresource, CHARINDEX('' (LATCH '', sp2.waitresource) - 1) ELSE RTRIM(sp2.waitresource) END`.

A separate future improvement could make use of the new latch info.

If the proposed fix is acceptable, I can send a PR.

### PR DESCRIPTION
**Pull request by dimitri-furman**
Fixes #56

### CODE REVIEW

**Comment by amachanic** [comment]
@dimitri-furman It looks like this only covers the sysprocesses case. Which other DMVs are impacted? Can you make sure we handle all necessary cases here? I also made a little mod to the code to make it a touch faster and less repeated.

**Comment by dimitri-furman** [comment]
@amachanic two other columns where new data will appear are: wait_resource in sys.dm_exec_requests and resource_description in sys.dm_os_waiting_tasks. After a quick glance at sp_whoisactive code, I don't think that will be a problem. But I haven't looked too closely, so similar change might be needed there too.

Thanks for the mod, that's better (haven't seen this use of APPLY before, thanks).

**Comment by amachanic** [comment]
@dimitri-furman Can you try on an impacted build, using `@get_task_info = 2` ?

**Comment by dimitri-furman** [comment]
> Can you try on an impacted build, using `@get_task_info = 2` ?

Yes, we do need a change there too:

```
Msg 245, Level 16, State 1, Line 339
Conversion failed when converting the nvarchar value ' 1)' to data type int.
```

I can try to do this, but likely not this week.

**Comment by amachanic** [comment]
@dimitri-furman I went ahead and plugged it in following the same pattern, assuming that the same format will be used in sys.dm_os_waiting_tasks, and that the latch info is tacked on to the end. Can you confirm? Thank you!

**Comment by dimitri-furman** [comment]
@amachanic yes, the format is the same. I ran the latest version on the same SQL build, no longer getting an error, so should be good to go.

**Pull request merged**
